// SPDX-FileCopyrightText: 2025 Gregory Neverov
// SPDX-License-Identifier: MIT

#pragma once

#define LOG_PID 0x01                    // Log the process ID with each message.
#define LOG_CONS 0x02                   // Log to the system console on error.
#define LOG_NDELAY 0x04                 // Connect to syslog daemon immediately.
#define LOG_ODELAY 0x08                 // Delay open until syslog() is called.
#define LOG_NOWAIT 0x10                 // Do not wait for child processes.

#define LOG_KERN 0                      // Reserved for message generated by the system.
#define LOG_USER 1                      // Message generated by a process.
#define LOG_MAIL 2                      // Reserved for message generated by mail system.
#define LOG_NEWS 3                      // Reserved for message generated by news system.
#define LOG_UUCP 4                      // Reserved for message generated by UUCP system.
#define LOG_DAEMON 5                    // Reserved for message generated by system daemon.
#define LOG_AUTH 6                      // Reserved for message generated by authorization daemon.
#define LOG_CRON 7                      // Reserved for message generated by clock daemon.
#define LOG_LPR 8                       // Reserved for message generated by printer system.
#define LOG_LOCAL0 9                    // Reserved for local use.
#define LOG_LOCAL1 10                   // Reserved for local use.
#define LOG_LOCAL2 11                   // Reserved for local use.
#define LOG_LOCAL3 12                   // Reserved for local use.
#define LOG_LOCAL4 13                   // Reserved for local use.
#define LOG_LOCAL5 14                   // Reserved for local use.
#define LOG_LOCAL6 15                   // Reserved for local use.
#define LOG_LOCAL7 16                   // Reserved for local use.

#define	LOG_MASK(pri) (1 << (pri))		// A mask for priority pri.
#define	LOG_UPTO(pri) ((1 << ((pri) + 1)) - 1)	// A mask for all priorities from LOG_EMERG through pri inclusive in the order listed in the list of priority symbolic constants below.

#define LOG_EMERG 0                     // A panic condition was reported to all processes.
#define LOG_ALERT 1                     // A condition that should be corrected immediately.
#define LOG_CRIT 2                      // A critical condition.
#define LOG_ERR 3                       // An error message.
#define LOG_WARNING 4                   // A warning message.
#define LOG_NOTICE 5                    // A condition requiring special handling.
#define LOG_INFO 6                      // A general information message.
#define LOG_DEBUG 7                     // A message useful for debugging programs.


void closelog(void);
void openlog(const char *ident, int logopt, int facility);
int setlogmask(int maskpri);
void syslog(int priority, const char *message, ... /* arguments */);